/// <reference path="../pb_data/types.d.ts" />

migrate(
  (app) => {
    const users = app.findCollectionByNameOrId("users");

    const essayExamples = new Collection({
      createRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id = user",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text_rs_essays_id",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-zA-Z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_rs_essays_domain",
          max: 0,
          min: 0,
          name: "moodle_domain",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "number_rs_essays_course",
          max: null,
          min: null,
          name: "course_id",
          onlyInt: true,
          presentable: false,
          required: true,
          system: false,
          type: "number",
        },
        {
          hidden: false,
          id: "number_rs_essays_quiz",
          max: null,
          min: null,
          name: "quiz_id",
          onlyInt: true,
          presentable: false,
          required: true,
          system: false,
          type: "number",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_rs_essays_qid",
          max: 0,
          min: 0,
          name: "question_id",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_rs_essays_qhash",
          max: 0,
          min: 0,
          name: "question_hash",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_rs_essays_qtype",
          max: 0,
          min: 0,
          name: "question_type",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_rs_essays_qtext",
          max: 2000,
          min: 0,
          name: "question_text",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_rs_essays_body",
          max: 20000,
          min: 0,
          name: "body",
          pattern: "",
          presentable: true,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          cascadeDelete: true,
          collectionId: users.id,
          hidden: false,
          id: "rel_rs_essays_user",
          maxSelect: 1,
          minSelect: 0,
          name: "user",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
        {
          hidden: false,
          id: "number_rs_essays_vu",
          max: null,
          min: null,
          name: "votes_up",
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: "number",
        },
        {
          hidden: false,
          id: "number_rs_essays_vd",
          max: null,
          min: null,
          name: "votes_down",
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: "number",
        },
        {
          hidden: false,
          id: "autodate_rs_essays_created",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate_rs_essays_updated",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      id: "pbc_rs_essays",
      indexes: [
        'CREATE UNIQUE INDEX "idx_reduxshare_essay_examples_identity" ON "reduxshare_essay_examples" ("user", "moodle_domain", "course_id", "quiz_id", "question_id", "question_hash")',
        'CREATE INDEX "idx_reduxshare_essay_examples_lookup" ON "reduxshare_essay_examples" ("moodle_domain", "course_id", "quiz_id", "question_id")',
      ],
      listRule: "@request.auth.id != ''",
      name: "reduxshare_essay_examples",
      system: false,
      type: "base",
      updateRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
    });
    app.save(essayExamples);

    const essayVotes = new Collection({
      createRule: "@request.auth.id != '' && @request.auth.id = user",
      deleteRule: "@request.auth.id = user",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text_rs_essayvotes_id",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-zA-Z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          cascadeDelete: true,
          collectionId: users.id,
          hidden: false,
          id: "rel_rs_essayvotes_user",
          maxSelect: 1,
          minSelect: 0,
          name: "user",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
        {
          cascadeDelete: true,
          collectionId: essayExamples.id,
          hidden: false,
          id: "rel_rs_essayvotes_example",
          maxSelect: 1,
          minSelect: 0,
          name: "example",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
        {
          hidden: false,
          id: "number_rs_essayvotes_value",
          max: null,
          min: null,
          name: "value",
          onlyInt: true,
          presentable: false,
          required: true,
          system: false,
          type: "number",
        },
        {
          hidden: false,
          id: "autodate_rs_essayvotes_created",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate_rs_essayvotes_updated",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      id: "pbc_rs_essayvotes",
      indexes: [
        'CREATE UNIQUE INDEX "idx_reduxshare_essay_votes_identity" ON "reduxshare_essay_votes" ("user", "example")',
      ],
      listRule: "@request.auth.id != ''",
      name: "reduxshare_essay_votes",
      system: false,
      type: "base",
      updateRule: "@request.auth.id != '' && @request.auth.id = user",
      viewRule: "@request.auth.id != ''",
    });
    app.save(essayVotes);
  },
  (app) => {
    app.delete(app.findCollectionByNameOrId("reduxshare_essay_votes"));
    app.delete(app.findCollectionByNameOrId("reduxshare_essay_examples"));
  },
);
